-- GENERATED by scripts/build-seed.mjs from data/departments.json and data/courses.json.
-- DO NOT EDIT. Change the JSON, then run `npm run db:seed` and commit both.
-- CI regenerates this file and fails if it differs from what is committed.
--
-- Starter data only (W3, ADR 0008): a handful of departments and courses so
-- the pickers are not empty. Users add the rest. Seeded rows have no
-- created_by. Loaded by `supabase db reset` locally; the hosted project
-- needs `supabase db push --include-seed` (see the root README).
--
-- `on conflict do nothing` makes re-running this harmless, including
-- against a database where users have already created some of these rows.
-- It also means a changed name or title here does not overwrite an existing
-- row.

insert into public.departments (code, name) values
  ('BSCI', 'Biological Sciences'),
  ('CHEM', 'Chemistry'),
  ('CS', 'Computer Science'),
  ('DS', 'Data Science'),
  ('ECE', 'Electrical & Computer Engineering'),
  ('ECON', 'Economics'),
  ('ES', 'Engineering Science'),
  ('MATH', 'Mathematics'),
  ('PHYS', 'Physics'),
  ('PSY', 'Psychology (AS)')
on conflict (code) do nothing;

insert into public.courses (department_code, number, title) values
  ('BSCI', '1510', 'Molecules and Cells'),
  ('BSCI', '1511', 'Organisms and Ecosystems'),
  ('CHEM', '1601', 'General Chemistry'),
  ('CHEM', '1601L', 'General Chemistry Laboratory'),
  ('CHEM', '1602', 'General Chemistry'),
  ('CS', '2201', 'Program Design and Data Structures'),
  ('CS', '2212', 'Discrete Structures'),
  ('CS', '3251', 'Intermediate Software Design'),
  ('CS', '4278', 'Principles of Software Engineering'),
  ('DS', '1000', 'Data Science: How Data Shape Our World'),
  ('DS', '3100', 'Fundamentals of Data Science'),
  ('ECE', '2123', 'Digital Systems'),
  ('ECE', '2281', 'Computer Architecture'),
  ('ECE', '2281L', 'Computer Architecture Laboratory'),
  ('ECON', '1010', 'Principles of Macroeconomics'),
  ('ECON', '1020', 'Principles of Microeconomics'),
  ('ES', '1401', 'Introduction to Engineering, Module 1'),
  ('ES', '2100W', 'Technical Communications'),
  ('MATH', '1300', 'Accelerated Single-Variable Calculus I'),
  ('MATH', '1301', 'Accelerated Single-Variable Calculus II'),
  ('MATH', '2410', 'Methods of Linear Algebra'),
  ('MATH', '2810', 'Probability and Statistics for Engineering'),
  ('PHYS', '1601', 'General Physics I'),
  ('PHYS', '1601L', 'General Physics Laboratory I'),
  ('PHYS', '1602', 'General Physics II'),
  ('PSY', '1200', 'General Psychology'),
  ('PSY', '2150', 'Principles of Experimental Design')
on conflict (department_code, number) do nothing;
